/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedAdminsRouteImport } from './routes/_authed/admins'
import { Route as AuthedAuditRouteImport } from './routes/_authed/audit'
import { Route as AuthedProxiesRouteImport } from './routes/_authed/proxies'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedAccountsIndexRouteImport } from './routes/_authed/accounts/index'
import { Route as AuthedAccountsIdRouteImport } from './routes/_authed/accounts/$id'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminsRoute = AuthedAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAuditRoute = AuthedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProxiesRoute = AuthedProxiesRouteImport.update({
  id: '/proxies',
  path: '/proxies',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountsIndexRoute = AuthedAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountsIdRoute = AuthedAccountsIdRouteImport.update({
  id: '/accounts/$id',
  path: '/accounts/$id',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/admins': typeof AuthedAdminsRoute
  '/audit': typeof AuthedAuditRoute
  '/proxies': typeof AuthedProxiesRoute
  '/settings': typeof AuthedSettingsRoute
  '/accounts/$id': typeof AuthedAccountsIdRoute
  '/accounts/': typeof AuthedAccountsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/admins': typeof AuthedAdminsRoute
  '/audit': typeof AuthedAuditRoute
  '/proxies': typeof AuthedProxiesRoute
  '/settings': typeof AuthedSettingsRoute
  '/': typeof AuthedIndexRoute
  '/accounts/$id': typeof AuthedAccountsIdRoute
  '/accounts': typeof AuthedAccountsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/admins': typeof AuthedAdminsRoute
  '/_authed/audit': typeof AuthedAuditRoute
  '/_authed/proxies': typeof AuthedProxiesRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/accounts/$id': typeof AuthedAccountsIdRoute
  '/_authed/accounts/': typeof AuthedAccountsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admins'
    | '/audit'
    | '/proxies'
    | '/settings'
    | '/accounts/$id'
    | '/accounts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/admins'
    | '/audit'
    | '/proxies'
    | '/settings'
    | '/'
    | '/accounts/$id'
    | '/accounts'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/admins'
    | '/_authed/audit'
    | '/_authed/proxies'
    | '/_authed/settings'
    | '/_authed/'
    | '/_authed/accounts/$id'
    | '/_authed/accounts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admins': {
      id: '/_authed/admins'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof AuthedAdminsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/audit': {
      id: '/_authed/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthedAuditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/proxies': {
      id: '/_authed/proxies'
      path: '/proxies'
      fullPath: '/proxies'
      preLoaderRoute: typeof AuthedProxiesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/accounts/': {
      id: '/_authed/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AuthedAccountsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/accounts/$id': {
      id: '/_authed/accounts/$id'
      path: '/accounts/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AuthedAccountsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAdminsRoute: typeof AuthedAdminsRoute
  AuthedAuditRoute: typeof AuthedAuditRoute
  AuthedProxiesRoute: typeof AuthedProxiesRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedAccountsIdRoute: typeof AuthedAccountsIdRoute
  AuthedAccountsIndexRoute: typeof AuthedAccountsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminsRoute: AuthedAdminsRoute,
  AuthedAuditRoute: AuthedAuditRoute,
  AuthedProxiesRoute: AuthedProxiesRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedAccountsIdRoute: AuthedAccountsIdRoute,
  AuthedAccountsIndexRoute: AuthedAccountsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
